/* 개인회원 */
CREATE TABLE MEMBER (
	USER_NO VARCHAR2(30) NOT NULL, /* 회원번호 */
	USER_ID VARCHAR2(100), /* 아이디 */
	PWD VARCHAR2(150), /* 비밀번호 */
	USER_NAME VARCHAR2(50), /* 이름 */
	IMAGEURL VARCHAR2(100), /* 프로필URL */
	NICKNAME VARCHAR2(50), /* 별명 */
	BIRTH VARCHAR2(50), /* 생년월일 */
	GENDER VARCHAR2(10), /* 성별 */
	ZIPCODE VARCHAR2(10), /* 우편번호 */
	ADDRESS VARCHAR2(100), /* 주소 */
	ADDRESS_DETAIL VARCHAR2(100), /* 상세주소 */
	EMAIL VARCHAR2(100), /* 이메일 */
	HP VARCHAR2(50), /* 연락처 */
	REGDATE VARCHAR2(50) DEFAULT sysdate, /* 가입일 */
	OUTDATE VARCHAR2(50), /* 탈퇴일 */
	USER_STATUS VARCHAR2(50) DEFAULT 'U', /* 유저상태 */
	RESUME_NO NUMBER, /* 대표이력서번호 */
	YORN VARCHAR2(4) /* 이력서공개여부 */
);

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		USER_NO ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			USER_NO
		);

/* 이력서 */
CREATE TABLE RESUME (
	RESUME_NO NUMBER NOT NULL, /* 이력서번호 */
	USER_NO VARCHAR2(30) NOT NULL, /* 회원번호 */
	LOCATION1 VARCHAR2(50), /* 희망근무지1 */
	LOCATION2 VARCHAR2(50), /* 희망근무지2 */
	SAL VARCHAR2(400), /* 희망연봉 */
	JOBTYPE1 VARCHAR2(50), /* 희망직종1 */
	JOBTYPE2 VARCHAR2(50), /* 희망직종2 */
	SELF_INT_TITLE VARCHAR2(100), /* 자기소개제목 */
	SELF_INT CLOB, /* 자기소개 */
	REGDATE DATE DEFAULT sysdate /* 등록일자 */
);

CREATE UNIQUE INDEX resume
	ON RESUME (
		RESUME_NO ASC
	);

ALTER TABLE RESUME
	ADD
		CONSTRAINT resume
		PRIMARY KEY (
			RESUME_NO
		);

/* 관리자 */
CREATE TABLE ADMIN (
	ADMIN_NO NUMBER NOT NULL, /* 관리자번호 */
	ADMIN_ID VARCHAR2(100), /* 아이디 */
	PWD VARCHAR2(100), /* 비밀번호 */
	ADMIN_NAME VARCHAR2(50), /* 이름 */
	TEL VARCHAR2(50), /* 연락처 */
	LEVELS NUMBER, /* 관리등급 */
	REGDATE DATE DEFAULT sysdate /* 등록일 */
);

CREATE UNIQUE INDEX PK_ADMIN
	ON ADMIN (
		ADMIN_NO ASC
	);

ALTER TABLE ADMIN
	ADD
		CONSTRAINT PK_ADMIN
		PRIMARY KEY (
			ADMIN_NO
		);

/* 관리자등급 */
CREATE TABLE ADMINLEVEL (
	LEVELS NUMBER NOT NULL, /* 관리등급 */
	LEVEL_NAME VARCHAR2(50) /* 등급이름 */
);

CREATE UNIQUE INDEX PK_ADMINLEVEL
	ON ADMINLEVEL (
		LEVELS ASC
	);

ALTER TABLE ADMINLEVEL
	ADD
		CONSTRAINT PK_ADMINLEVEL
		PRIMARY KEY (
			LEVELS
		);

/* 공지사항 */
CREATE TABLE NOTICE (
	NOTICE_NO NUMBER NOT NULL, /* 글번호 */
	TITLE VARCHAR2(100), /* 제목 */
	TYPE VARCHAR2(100), /* 구분 */
	CONTENT CLOB, /* 내용 */
	READCOUNT NUMBER DEFAULT 0, /* 조회수 */
	REGDATE DATE DEFAULT sysdate, /* 등록일 */
	FILENAME VARCHAR2(100), /* 업로드 된 파일 이름 */
	FILESIZE NUMBER, /* 업로드 된 파일 사이즈 */
	ORIGINFILENAME VARCHAR2(100), /* 파일 원본 이름 */
	MEMBER_TYPE VARCHAR2(10) /* 회원타입 */
);

CREATE UNIQUE INDEX PK_NOTICE
	ON NOTICE (
		NOTICE_NO ASC
	);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT PK_NOTICE
		PRIMARY KEY (
			NOTICE_NO
		);

/* FaQ */
CREATE TABLE FaQ (
	FAQ_NO NUMBER NOT NULL, /* 번호 */
	CATEGORY VARCHAR2(200), /* 카테고리 */
	QUESTION VARCHAR2(200), /* 질문 */
	ANSWER CLOB /* 답변 */
);

CREATE UNIQUE INDEX PK_FaQ
	ON FaQ (
		FAQ_NO ASC
	);

ALTER TABLE FaQ
	ADD
		CONSTRAINT PK_FaQ
		PRIMARY KEY (
			FAQ_NO
		);

/* 서비스기간 */
CREATE TABLE TOS (
	SERVICE_CODE VARCHAR2(30) NOT NULL, /* 서비스번호 */
	START_DATE VARCHAR2(100), /* 등록일 */
	END_DATE VARCHAR2(100), /* 마감일 */
	RECRUITMENT_CODE VARCHAR2(30) /* 채용정보코드 */
);

CREATE UNIQUE INDEX PK_TOS
	ON TOS (
		SERVICE_CODE ASC
	);

ALTER TABLE TOS
	ADD
		CONSTRAINT PK_TOS
		PRIMARY KEY (
			SERVICE_CODE
		);

/* 채용스크랩 */
CREATE TABLE COMSCRAP (
	SCRAP_NO NUMBER, /* 스크랩번호 */
	USER_NO VARCHAR2(30), /* 회원번호 */
	RECRUITMENT_CODE VARCHAR2(30) /* 채용정보코드 */
);

/* 인재스크랩 */
CREATE TABLE PERSCRAP (
	SCRAP_NO NUMBER, /* 스크랩번호 */
	RESUME_NO NUMBER, /* 이력서번호 */
	C_MEMBER_CODE VARCHAR2(30) /* 기업회원코드 */
);

/* 채용정보 */
CREATE TABLE RECRUITMENT (
	RECRUITMENT_CODE VARCHAR2(30) NOT NULL, /* 채용정보코드 */
	COM_NAME VARCHAR2(100), /* 기업명 */
	TITLE VARCHAR2(100), /* 제목 */
	JOB_TYPE1 VARCHAR2(100), /* 직무 */
	JOB_TYPE2 VARCHAR2(100), /* 직무2 */
	INDU_TYPE1 VARCHAR2(100), /* 산업 */
	INDU_TYPE2 VARCHAR2(100), /* 산업2 */
	ZIPCODE VARCHAR2(100), /* 우편번호 */
	ADDRESS VARCHAR2(200), /* 주소 */
	ADDRESSDETAIL VARCHAR2(200), /* 상세주소 */
	LOCATION1 VARCHAR2(30), /* 지역 */
	LOCATION2 VARCHAR2(30), /* 상세지역 */
	WORKHOURS VARCHAR2(30), /* 근무시간 */
	PAY VARCHAR2(100), /* 급여 */
	REC_TYPE VARCHAR2(100), /* 근무형태 */
	WELFARE VARCHAR2(300), /* 복리후생 */
	GENDER VARCHAR2(25), /* 성별 */
	AGE VARCHAR2(50), /* 연령 */
	EDUCATION_LV VARCHAR2(100), /* 학력조건 */
	CAREER VARCHAR2(100), /* 경력사항 */
	PREFERENCE VARCHAR2(300), /* 우대조건 */
	REC_NUMBER VARCHAR2(30), /* 모집인원 */
	REGDATE DATE, /* 등록일 */
	DOCUMENT VARCHAR2(100), /* 제출서류 */
	REC_DETAIL CLOB, /* 상세모집요강 */
	READCOUNT NUMBER DEFAULT 0, /* 조회수 */
	ACCUSE VARCHAR2(100), /* 신고여부 */
	CATEGORY VARCHAR2(100), /* 카테고리 */
	IMGURL VARCHAR2(100), /* 이미지 */
	FILENAME VARCHAR2(100), /* 파일명 */
	FILESIZE VARCHAR2(100), /* 파일크기 */
	COM_TYPE VARCHAR2(100), /* 기업 형태 */
	COM_CODE VARCHAR2(100), /* 회사코드 */
	RESUME_TYPE NUMBER /* 이력서형식 */
);

CREATE UNIQUE INDEX PK_RECRUITMENT
	ON RECRUITMENT (
		RECRUITMENT_CODE ASC
	);

ALTER TABLE RECRUITMENT
	ADD
		CONSTRAINT PK_RECRUITMENT
		PRIMARY KEY (
			RECRUITMENT_CODE
		);

/* 회사정보 */
CREATE TABLE COMPANY_INFO (
	COM_CODE VARCHAR2(100) NOT NULL, /* 회사코드 */
	COM_NAME VARCHAR2(30), /* 회사명 */
	CEO VARCHAR2(30), /* 대표자명 */
	COM_NUM VARCHAR2(30), /* 사업자등록번호 */
	ZIPCODE VARCHAR2(100), /* 우편번호 */
	ADDRESS VARCHAR2(100), /* 주소 */
	ADDRESSDETAIL VARCHAR2(100), /* 상세주소 */
	IMAGEURL VARCHAR2(30), /* 회사사진 */
	COM_HP VARCHAR2(30), /* 전화번호 */
	COM_TYPE VARCHAR2(100), /* 회사분류 */
	COM_INDUSTRY VARCHAR2(100), /* 회사업종 */
	CONTENT VARCHAR2(300), /* 주요사업내용 */
	HOMEPAGE VARCHAR2(50), /* 홈페이지 */
	C_MEMBER_CODE VARCHAR2(30) /* 기업회원코드 */
);

CREATE UNIQUE INDEX PK_COMPANY_INFO
	ON COMPANY_INFO (
		COM_CODE ASC
	);

ALTER TABLE COMPANY_INFO
	ADD
		CONSTRAINT PK_COMPANY_INFO
		PRIMARY KEY (
			COM_CODE
		);

/* 1:1문의 */
CREATE TABLE QnA (
	QNA_NO NUMBER NOT NULL, /* 글번호 */
	USER_NO VARCHAR2(30), /* 회원번호 */
	USER_ID VARCHAR2(100), /* 아이디 */
	TITLE VARCHAR2(100), /* 제목 */
	CATEGORY_NO NUMBER, /* 카테고리번호 */
	CONTENT CLOB, /* 내용 */
	REGDATE DATE DEFAULT SYSDATE, /* 등록일 */
	FILENAME VARCHAR2(100), /* 업로드 된 파일 이름 */
	FILESIZE NUMBER, /* 업로드 된 파일 사이즈 */
	ORIGINFILENAME VARCHAR2(100), /* 파일 원본 이름 */
	STATUS VARCHAR2(50) /* 회원구분 */
);

CREATE UNIQUE INDEX PK_QnA
	ON QnA (
		QNA_NO ASC
	);

ALTER TABLE QnA
	ADD
		CONSTRAINT PK_QnA
		PRIMARY KEY (
			QNA_NO
		);

/* 문의카테고리 */
CREATE TABLE QCATEGORY (
	CATEGORY_NO NUMBER NOT NULL, /* 카테고리번호 */
	CATEGORY_NAME VARCHAR2(50) /* 카테고리이름 */
);

CREATE UNIQUE INDEX PK_QCATEGORY
	ON QCATEGORY (
		CATEGORY_NO ASC
	);

ALTER TABLE QCATEGORY
	ADD
		CONSTRAINT PK_QCATEGORY
		PRIMARY KEY (
			CATEGORY_NO
		);

/* 지원현황 */
CREATE TABLE APPLY (
	APPLY_CODE NUMBER NOT NULL, /* 지원코드 */
	REGDATE DATE DEFAULT SYSDATE, /* 지원일 */
	CONTENT VARCHAR2(30), /* 지원내역 */
	STATUS VARCHAR2(30), /* 지원상태 */
	MEMO CLOB, /* 메모 */
	USER_NO VARCHAR2(30), /* 회원번호 */
	READ_CHECK VARCHAR2(30) /* 열람여부 */
);

CREATE UNIQUE INDEX PK_APPLY
	ON APPLY (
		APPLY_CODE ASC
	);

ALTER TABLE APPLY
	ADD
		CONSTRAINT PK_APPLY
		PRIMARY KEY (
			APPLY_CODE
		);

/* 지역 */
CREATE TABLE LOCATION (
	SIDO VARCHAR2(50), /* 시도 */
	SIGUGUN VARCHAR2(50) /* 시구군 */
);

/* 기업회원 */
CREATE TABLE COMPANY_MEMBER (
	C_MEMBER_CODE VARCHAR2(30) NOT NULL, /* 기업회원코드 */
	C_USERID VARCHAR2(30), /* 아이디 */
	C_PWD VARCHAR2(30), /* 비밀번호 */
	C_NICKNAME VARCHAR2(30), /* 닉네임 */
	C_USERNAME VARCHAR2(30), /* 이름 */
	C_BIRTH VARCHAR2(30), /* 생년월일 */
	C_GENDER VARCHAR2(10), /* 성별 */
	C_HP VARCHAR2(30), /* 휴대폰번호 */
	C_EMAIL VARCHAR2(30), /* 이메일 */
	C_JOINDATE VARCHAR2(100), /* 가입일 */
	C_USER_STATUS VARCHAR2(30) DEFAULT 'C', /* 유저상태 */
	C_OUTDATE VARCHAR2(100) /* 탈퇴일 */
);

CREATE UNIQUE INDEX PK_COMPANY_MEMBER
	ON COMPANY_MEMBER (
		C_MEMBER_CODE ASC
	);

ALTER TABLE COMPANY_MEMBER
	ADD
		CONSTRAINT PK_COMPANY_MEMBER
		PRIMARY KEY (
			C_MEMBER_CODE
		);

/* 직무대분류 */
CREATE TABLE JOB_LARGE (
	LARGE_NO NUMBER NOT NULL, /* 대분류번호 */
	LARGE_GROUP VARCHAR2(50) /* 대분류 */
);

CREATE UNIQUE INDEX PK_JOB_LARGE
	ON JOB_LARGE (
		LARGE_NO ASC
	);

ALTER TABLE JOB_LARGE
	ADD
		CONSTRAINT PK_JOB_LARGE
		PRIMARY KEY (
			LARGE_NO
		);

/* 직무중분류 */
CREATE TABLE JOB_MIDDLE (
	MIDDLE_NO NUMBER NOT NULL, /* 중분류번호 */
	MIDDLE_GROUP VARCHAR2(50), /* 중분류 */
	LARGE_NO NUMBER /* 대분류번호 */
);

CREATE UNIQUE INDEX PK_JOB_MIDDLE
	ON JOB_MIDDLE (
		MIDDLE_NO ASC
	);

ALTER TABLE JOB_MIDDLE
	ADD
		CONSTRAINT PK_JOB_MIDDLE
		PRIMARY KEY (
			MIDDLE_NO
		);

/* 산업대분류 */
CREATE TABLE INDUSTRY_LARGE (
	LARGE_NO NUMBER NOT NULL, /* 대분류번호 */
	LARGE_GROUP VARCHAR2(50) /* 대분류 */
);

CREATE UNIQUE INDEX PK_INDUSTRY_LARGE
	ON INDUSTRY_LARGE (
		LARGE_NO ASC
	);

ALTER TABLE INDUSTRY_LARGE
	ADD
		CONSTRAINT PK_INDUSTRY_LARGE
		PRIMARY KEY (
			LARGE_NO
		);

/* 산업중분류 */
CREATE TABLE INDUSTRY_MIDDLE (
	MIDDLE_NO NUMBER NOT NULL, /* 중분류번호 */
	MIDDLE_GROUP VARCHAR2(50), /* 중분류 */
	LARGE_NO NUMBER /* 대분류번호 */
);

CREATE UNIQUE INDEX PK_INDUSTRY_MIDDLE
	ON INDUSTRY_MIDDLE (
		MIDDLE_NO ASC
	);

ALTER TABLE INDUSTRY_MIDDLE
	ADD
		CONSTRAINT PK_INDUSTRY_MIDDLE
		PRIMARY KEY (
			MIDDLE_NO
		);

/* 자격증 */
CREATE TABLE CERTIFY (
	CERTIFY_CODE NUMBER NOT NULL, /* 고유코드 */
	CERTIFY_NAME VARCHAR2(50), /* 자격증명 */
	CERTIFY_PLACE VARCHAR2(50), /* 발행처/기관 */
	CERTIFY_GET_DATE VARCHAR2(50), /* 취득일 */
	RESUME_NO NUMBER /* 이력서번호 */
);

CREATE UNIQUE INDEX PK_CERTIFY
	ON CERTIFY (
		CERTIFY_CODE ASC
	);

ALTER TABLE CERTIFY
	ADD
		CONSTRAINT PK_CERTIFY
		PRIMARY KEY (
			CERTIFY_CODE
		);

/* 어학 */
CREATE TABLE LANGUAGE (
	LANG_CODE NUMBER NOT NULL, /* 고유코드 */
	KINDS VARCHAR2(100), /* 언어종류 */
	TEST_NAME VARCHAR2(100), /* 시험종류 */
	LANG_SCORE VARCHAR2(100), /* 점수 */
	RATING VARCHAR2(100), /* 급수 */
	LANG_GET_DATE VARCHAR2(100), /* 취득일 */
	RESUME_NO NUMBER /* 이력서번호 */
);

CREATE UNIQUE INDEX PK_LANGUAGE
	ON LANGUAGE (
		LANG_CODE ASC
	);

ALTER TABLE LANGUAGE
	ADD
		CONSTRAINT PK_LANGUAGE
		PRIMARY KEY (
			LANG_CODE
		);

/* 수상내역 */
CREATE TABLE AWARD (
	AWARD_NAME VARCHAR2(50), /* 수상명 */
	AWARD_GET_DATE VARCHAR2(50), /* 수상/공모일 */
	RESUME_NO NUMBER, /* 이력서번호 */
	AWARD_COM VARCHAR2(50), /* 수여기관 */
	AWARD_CODE NUMBER NOT NULL /* 고유코드 */
);

CREATE UNIQUE INDEX PK_AWARD
	ON AWARD (
		AWARD_CODE ASC
	);

ALTER TABLE AWARD
	ADD
		CONSTRAINT PK_AWARD
		PRIMARY KEY (
			AWARD_CODE
		);

/* 경력사항 */
CREATE TABLE CAREER (
	CAREER_CODE NUMBER NOT NULL, /* 고유코드 */
	CAREER_COMPANY VARCHAR2(50), /* 회사 */
	CAREER_PERIOD VARCHAR2(50), /* 근무기간 */
	CAREER_REASON VARCHAR2(50), /* 퇴사사유 */
	CAREER_RANK VARCHAR2(50), /* 직급 */
	CAREER_YEAR VARCHAR2(50), /* 연차 */
	CAREER_LOCATION VARCHAR2(50), /* 근무지역 */
	CAREER_SAL VARCHAR2(50), /* 연봉 */
	TASK VARCHAR2(50), /* 담당업무 */
	RESUME_NO NUMBER /* 이력서번호 */
);

CREATE UNIQUE INDEX PK_CAREER
	ON CAREER (
		CAREER_CODE ASC
	);

ALTER TABLE CAREER
	ADD
		CONSTRAINT PK_CAREER
		PRIMARY KEY (
			CAREER_CODE
		);

/* 개인부가정보 */
CREATE TABLE ADDINFO (
	INFO_CODE NUMBER NOT NULL, /* 고유코드 */
	DISABLE VARCHAR2(50), /* 장애여부 */
	MILITARY VARCHAR2(50), /* 병역사항 */
	AFFAIR VARCHAR2(50), /* 국가보훈 */
	S_FUND VARCHAR2(50), /* 고용지원금 */
	RESUME_NO NUMBER /* 이력서번호 */
);

CREATE UNIQUE INDEX PK_ADDINFO
	ON ADDINFO (
		INFO_CODE ASC
	);

ALTER TABLE ADDINFO
	ADD
		CONSTRAINT PK_ADDINFO
		PRIMARY KEY (
			INFO_CODE
		);

/* 학력 */
CREATE TABLE EDUCATION (
	EDU_CODE NUMBER NOT NULL, /* 고유코드 */
	FINAL_EDU VARCHAR2(100), /* 최종학력 */
	UNI VARCHAR2(100), /* 대학구분 */
	UNI_NAME VARCHAR2(100), /* 학교명 */
	EDU_LOCATION VARCHAR2(100), /* 지역 */
	EDU_PERIOD VARCHAR2(100), /* 재학기간 */
	MAJOR VARCHAR2(100), /* 전공 */
	EDU_SCORE VARCHAR2(50), /* 학점 */
	RESUME_NO NUMBER /* 이력서번호 */
);

CREATE UNIQUE INDEX PK_EDUCATION
	ON EDUCATION (
		EDU_CODE ASC
	);

ALTER TABLE EDUCATION
	ADD
		CONSTRAINT PK_EDUCATION
		PRIMARY KEY (
			EDU_CODE
		);

/* 대외할동 */
CREATE TABLE ACTIVE (
	ACT_CODE NUMBER NOT NULL, /* 고유코드 */
	ACTIVITY VARCHAR2(100), /* 활동구분 */
	ACT_PLACE VARCHAR2(100), /* 기관/장소 */
	ACT_PERIOD VARCHAR2(100), /* 활동기간 */
	ACT_CONTENT VARCHAR2(300), /* 활동내용 */
	RESUME_NO NUMBER /* 이력서번호 */
);

CREATE UNIQUE INDEX PK_ACTIVE
	ON ACTIVE (
		ACT_CODE ASC
	);

ALTER TABLE ACTIVE
	ADD
		CONSTRAINT PK_ACTIVE
		PRIMARY KEY (
			ACT_CODE
		);

/* 포트폴리오 */
CREATE TABLE POTFOLIO (
	POT_CODE NUMBER NOT NULL, /* 고유코드 */
	POT_FILE VARCHAR2(100), /* 파일 */
	POT_PERIOD VARCHAR2(100), /* 작업기간 */
	POT_TOOLS VARCHAR2(100), /* 작업툴 */
	WORKERS VARCHAR2(100), /* 작업인원 */
	INTRO CLOB, /* 작품소개 */
	RESUME_NO NUMBER /* 이력서번호 */
);

CREATE UNIQUE INDEX PK_POTFOLIO
	ON POTFOLIO (
		POT_CODE ASC
	);

ALTER TABLE POTFOLIO
	ADD
		CONSTRAINT PK_POTFOLIO
		PRIMARY KEY (
			POT_CODE
		);

/* 결제 */
CREATE TABLE PAYMENT (
	PAYMENT_CODE NUMBER NOT NULL, /* 결제 코드 */
	PRODUCT_NAME VARCHAR2(300), /* 결제상품명 */
	PRICE NUMBER, /* 가격 */
	REGDATE VARCHAR2(300), /* 등록일 */
	C_MEMBER_CODE VARCHAR2(30) /* 기업회원코드 */
);

CREATE UNIQUE INDEX PK_PAYMENT
	ON PAYMENT (
		PAYMENT_CODE ASC
	);

ALTER TABLE PAYMENT
	ADD
		CONSTRAINT PK_PAYMENT
		PRIMARY KEY (
			PAYMENT_CODE
		);

/* FaQC */
CREATE TABLE FaQC (
	FAQ_NO NUMBER NOT NULL, /* 번호 */
	CATEGORY VARCHAR2(200), /* 카테고리 */
	QUESTION VARCHAR2(200), /* 질문 */
	ANSWER CLOB /* 답변 */
);

CREATE UNIQUE INDEX PK_FaQC
	ON FaQC (
		FAQ_NO ASC
	);

ALTER TABLE FaQC
	ADD
		CONSTRAINT PK_FaQC
		PRIMARY KEY (
			FAQ_NO
		);

/* QNA리뷰 */
CREATE TABLE QNARE (
	NO NUMBER NOT NULL, /* 번호 */
	NAME VARCHAR2(100), /* 이름 */
	REGDATE DATE DEFAULT sysdate, /* 등록일 */
	CONTENT CLOB, /* 내용 */
	QNA_NO NUMBER /* 글번호 */
);

CREATE UNIQUE INDEX PK_QNARE
	ON QNARE (
		NO ASC
	);

ALTER TABLE QNARE
	ADD
		CONSTRAINT PK_QNARE
		PRIMARY KEY (
			NO
		);

/* 자사이력서사용 */
CREATE TABLE COMPANY_RESUMEUSE  (
	USER_ID VARCHAR2(100) NOT NULL, /* 아이디 */
	GENDER VARCHAR2(10), /* 성별 */
	EMAIL VARCHAR2(100), /* 이메일 */
	HP VARCHAR2(50), /* 전화번호 */
	BIRTH VARCHAR2(50), /* 생년월일 */
	ZIPCODE VARCHAR2(10), /* 우편번호 */
	ADDRESS VARCHAR2(100), /* 주소 */
	ADDRESS_DETAIL VARCHAR2(100), /* 상세주소 */
	EDU VARCHAR2(900), /* 학력 */
	CAREER VARCHAR2(900), /* 경력 */
	CERTIFICATE VARCHAR2(900), /* 자격증 */
	LANGUAGE VARCHAR2(900), /* 어학 */
	AWARD VARCHAR2(900), /* 수상경력 */
	SPECIAL VARCHAR2(900), /* 우대사항 */
	ACTIVITY VARCHAR2(900), /* 대외활동 */
	SELF1 CLOB, /* 자기소개서1 */
	SELF2 CLOB, /* 자기소개서2 */
	SELF3 CLOB, /* 자기소개서3 */
	SELF4 CLOB, /* 자기소개서4 */
	SELF5 CLOB, /* 자기소개서5 */
	NAME VARCHAR2(30), /* 이름 */
	RECRUITMENT_CODE VARCHAR2(30) /* 채용정보코드 */
);

CREATE UNIQUE INDEX PK_COMPANY_RESUMEUSE 
	ON COMPANY_RESUMEUSE  (
		USER_ID ASC
	);

ALTER TABLE COMPANY_RESUMEUSE 
	ADD
		CONSTRAINT PK_COMPANY_RESUMEUSE 
		PRIMARY KEY (
			USER_ID
		);

/* 자사이력서설정 */
CREATE TABLE COMPANY_RESUMESET  (
	RECRUITMENT_CODE VARCHAR2(30) NOT NULL, /* 채용정보코드 */
	SCHOOLVAL VARCHAR2(30), /* 학력사용여부 */
	CAREERVAL VARCHAR2(30), /* 경력사용여부 */
	CERTIFICATEVAL VARCHAR2(30), /* 자격증사용여부 */
	LANGUAGEVAL VARCHAR2(30), /* 어학사용여부 */
	AWARDSVAL VARCHAR2(30), /* 수상경력사용여부 */
	SPECIALVAL VARCHAR2(30), /* 우대사항사용여부 */
	ACTIVITYVAL  VARCHAR2(30), /* 대외활동사용여부 */
	SELFVAL VARCHAR2(30), /* 자기소개서사용여부 */
	SELFTITLE1 VARCHAR2(300), /* 자기소개서주제1 */
	SELFTITLE2 VARCHAR2(300), /* 자기소개서주제2 */
	SELFTITLE3 VARCHAR2(300), /* 자기소개서주제3 */
	SELFTITLE4 VARCHAR2(300), /* 자기소개서주제4 */
	SELFTITLE5 VARCHAR2(300) /* 자기소개서주제5 */
);

CREATE UNIQUE INDEX PK_COMPANY_RESUMESET 
	ON COMPANY_RESUMESET  (
		RECRUITMENT_CODE ASC
	);

ALTER TABLE COMPANY_RESUMESET 
	ADD
		CONSTRAINT PK_COMPANY_RESUMESET 
		PRIMARY KEY (
			RECRUITMENT_CODE
		);

ALTER TABLE RESUME
	ADD
		CONSTRAINT FK_MEMBER_TO_RESUME
		FOREIGN KEY (
			USER_NO
		)
		REFERENCES MEMBER (
			USER_NO
		);

ALTER TABLE ADMIN
	ADD
		CONSTRAINT FK_ADMINLEVEL_TO_ADMIN
		FOREIGN KEY (
			LEVELS
		)
		REFERENCES ADMINLEVEL (
			LEVELS
		);

ALTER TABLE TOS
	ADD
		CONSTRAINT FK_RECRUITMENT_TO_TOS
		FOREIGN KEY (
			RECRUITMENT_CODE
		)
		REFERENCES RECRUITMENT (
			RECRUITMENT_CODE
		);

ALTER TABLE COMSCRAP
	ADD
		CONSTRAINT FK_MEMBER_TO_COMSCRAP
		FOREIGN KEY (
			USER_NO
		)
		REFERENCES MEMBER (
			USER_NO
		);

ALTER TABLE COMSCRAP
	ADD
		CONSTRAINT FK_RECRUITMENT_TO_COMSCRAP
		FOREIGN KEY (
			RECRUITMENT_CODE
		)
		REFERENCES RECRUITMENT (
			RECRUITMENT_CODE
		);

ALTER TABLE PERSCRAP
	ADD
		CONSTRAINT FK_RESUME_TO_PERSCRAP
		FOREIGN KEY (
			RESUME_NO
		)
		REFERENCES RESUME (
			RESUME_NO
		);

ALTER TABLE PERSCRAP
	ADD
		CONSTRAINT FK_COMPANY_MEMBER_TO_PERSCRAP
		FOREIGN KEY (
			C_MEMBER_CODE
		)
		REFERENCES COMPANY_MEMBER (
			C_MEMBER_CODE
		);

ALTER TABLE RECRUITMENT
	ADD
		CONSTRAINT FK_COMPANY_INFO_TO_RECRUITMENT
		FOREIGN KEY (
			COM_CODE
		)
		REFERENCES COMPANY_INFO (
			COM_CODE
		);

ALTER TABLE COMPANY_INFO
	ADD
		CONSTRAINT FK_COMPANY_MEMBER_TO_COMPANY_INFO
		FOREIGN KEY (
			C_MEMBER_CODE
		)
		REFERENCES COMPANY_MEMBER (
			C_MEMBER_CODE
		);

ALTER TABLE QnA
	ADD
		CONSTRAINT FK_MEMBER_TO_QnA
		FOREIGN KEY (
			USER_NO
		)
		REFERENCES MEMBER (
			USER_NO
		);

ALTER TABLE QnA
	ADD
		CONSTRAINT FK_QCATEGORY_TO_QnA
		FOREIGN KEY (
			CATEGORY_NO
		)
		REFERENCES QCATEGORY (
			CATEGORY_NO
		);

ALTER TABLE APPLY
	ADD
		CONSTRAINT FK_MEMBER_TO_APPLY
		FOREIGN KEY (
			USER_NO
		)
		REFERENCES MEMBER (
			USER_NO
		);

ALTER TABLE JOB_MIDDLE
	ADD
		CONSTRAINT FK_JOB_LARGE_TO_JOB_MIDDLE
		FOREIGN KEY (
			LARGE_NO
		)
		REFERENCES JOB_LARGE (
			LARGE_NO
		);

ALTER TABLE INDUSTRY_MIDDLE
	ADD
		CONSTRAINT FK_INDUSTRY_LARGE_TO_INDUSTRY_MIDDLE
		FOREIGN KEY (
			LARGE_NO
		)
		REFERENCES INDUSTRY_LARGE (
			LARGE_NO
		);

ALTER TABLE CERTIFY
	ADD
		CONSTRAINT FK_RESUME_TO_CERTIFY
		FOREIGN KEY (
			RESUME_NO
		)
		REFERENCES RESUME (
			RESUME_NO
		);

ALTER TABLE LANGUAGE
	ADD
		CONSTRAINT FK_RESUME_TO_LANGUAGE
		FOREIGN KEY (
			RESUME_NO
		)
		REFERENCES RESUME (
			RESUME_NO
		);

ALTER TABLE AWARD
	ADD
		CONSTRAINT FK_RESUME_TO_AWARD
		FOREIGN KEY (
			RESUME_NO
		)
		REFERENCES RESUME (
			RESUME_NO
		);

ALTER TABLE CAREER
	ADD
		CONSTRAINT FK_RESUME_TO_CAREER
		FOREIGN KEY (
			RESUME_NO
		)
		REFERENCES RESUME (
			RESUME_NO
		);

ALTER TABLE ADDINFO
	ADD
		CONSTRAINT FK_RESUME_TO_ADDINFO
		FOREIGN KEY (
			RESUME_NO
		)
		REFERENCES RESUME (
			RESUME_NO
		);

ALTER TABLE EDUCATION
	ADD
		CONSTRAINT FK_RESUME_TO_EDUCATION
		FOREIGN KEY (
			RESUME_NO
		)
		REFERENCES RESUME (
			RESUME_NO
		);

ALTER TABLE ACTIVE
	ADD
		CONSTRAINT FK_RESUME_TO_ACTIVE
		FOREIGN KEY (
			RESUME_NO
		)
		REFERENCES RESUME (
			RESUME_NO
		);

ALTER TABLE POTFOLIO
	ADD
		CONSTRAINT FK_RESUME_TO_POTFOLIO
		FOREIGN KEY (
			RESUME_NO
		)
		REFERENCES RESUME (
			RESUME_NO
		);

ALTER TABLE PAYMENT
	ADD
		CONSTRAINT FK_COMPANY_MEMBER_TO_PAYMENT
		FOREIGN KEY (
			C_MEMBER_CODE
		)
		REFERENCES COMPANY_MEMBER (
			C_MEMBER_CODE
		);

ALTER TABLE QNARE
	ADD
		CONSTRAINT FK_QnA_TO_QNARE
		FOREIGN KEY (
			QNA_NO
		)
		REFERENCES QnA (
			QNA_NO
		);

ALTER TABLE COMPANY_RESUMEUSE 
	ADD
		CONSTRAINT FK_RECRUITMENT_TO_COMPANY_RESUMEUSE 
		FOREIGN KEY (
			RECRUITMENT_CODE
		)
		REFERENCES RECRUITMENT (
			RECRUITMENT_CODE
		);

ALTER TABLE COMPANY_RESUMESET 
	ADD
		CONSTRAINT FK_RECRUITMENT_TO_COMPANY_RESUMESET 
		FOREIGN KEY (
			RECRUITMENT_CODE
		)
		REFERENCES RECRUITMENT (
			RECRUITMENT_CODE
		);